# used to test routes
GET http://localhost:8081/api/users/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmY2MzU3NWI4MTc3NzUyMTE4ZmM2ZiIsImlhdCI6MTY4NTAyMTUyN30.OHg4i-Fd-V4Mdm24CVqeL1vA0X_lXABhEmqmEp8gHF0

###
GET http://localhost:8081/api/users/cookie

###
OPTIONS http://localhost:8081/api/users/register

###
POST http://localhost:8081/api/users/register
Content-Type: application/json
credentials: "include"

{
    "emailAddress": "w1111ee@gmail.com",
    "phoneNumber": "111113",
    "password": "123"
}

###

GET http://localhost:3000/api/posts/645f4636e5b42a263b5df79c


###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab",
    "content_links": ["string1", "string2"]
}

###

PATCH http://localhost:3000/api/posts/645f4575e5b42a263b5df79a
Content-Type: application/json

{
    "content_links": "modifiedagain"
}

###

DELETE http://localhost:3000/api/posts/645f4575e5b42a263b5df79a

###

GET http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments

###

POST http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab",
    "content": "hello nice post 2"
}

###

DELETE http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments/645f8730d46e16b104456e2e

###

POST http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/like
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab"
}

###

DELETE http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/like
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab"
}