# used to test routes
GET http://localhost:8081/api/users

###
GET http://127.0.0.1:8081/api/forums/thread/get-threads/@dventur3
Cookie: blocalauth=localapi7e89e863624312e4:; isNotIncognito=true; _ga=GA1.1.1226195377.1678153685; authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODlhYzkxMTU0ZWQ0ZTcyYjlhNmExYiIsImlhdCI6MTY4Njc1NDQ2M30.qxrqANc74iNMKL9Soj4O6VuML0_eatr8EfESAkHdoSQ

###
OPTIONS http://localhost:8081/api/users/register

###
POST http://localhost:8081/api/users/register
Content-Type: application/json
credentials: "include"

{
    "emailAddress": "w1111ee@gmail.com",
    "phoneNumber": "111113",
    "password": "123"
}

###

GET http://localhost:3000/api/posts/645f4636e5b42a263b5df79c


###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab",
    "content_links": ["string1", "string2"]
}

###

PATCH http://localhost:3000/api/posts/645f4575e5b42a263b5df79a
Content-Type: application/json

{
    "content_links": "modifiedagain"
}

###

DELETE http://localhost:3000/api/posts/645f4575e5b42a263b5df79a

###

GET http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/comments

###

POST http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab",
    "content": "hello nice post 2"
}

###

DELETE http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments/645f8730d46e16b104456e2e

###

POST http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/like
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab"
}

###

DELETE http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/like
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab"
}

###

GET http://127.0.0.1:8081/api/posts/comments/647593717e5cbd1fba80f0db
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NTQ1ODk0M30.7QATwzOI8ERXAZPpLgsi0JGfOcMHqnl32IS53hdK9_8

###

DELETE http://127.0.0.1:8081/api/posts/likes/647593717e5cbd1fba80f0db
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NTQ1ODk0M30.7QATwzOI8ERXAZPpLgsi0JGfOcMHqnl32IS53hdK9_8

###

POST http://127.0.0.1:8081/api/posts/comments/647593717e5cbd1fba80f0db
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NTQ1ODk0M30.7QATwzOI8ERXAZPpLgsi0JGfOcMHqnl32IS53hdK9_8
Content-Type: application/json

{
    "content": "new comment",
    "creator_id": "6475929dd0b97c5c353602af"
}

###

GET http://127.0.0.1:8081/api/chats/latestMessages
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODU5Y2Y3OThlNjMzZjUwN2QzZDIyMiIsImlhdCI6MTY4NjczODcyOX0.D1_4ybHDMd_n9WP_xs6hXQhYL4s0u6AJ5NO3TPH6B-Q

###

GET http://127.0.0.1:8081/api/chats/648998fb867d47079cbd7f8f/2023-06-15T09%3A49%3A09.205%2B00%3A00/100
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODU5Y2Y3OThlNjMzZjUwN2QzZDIyMiIsImlhdCI6MTY4NjczODcyOX0.D1_4ybHDMd_n9WP_xs6hXQhYL4s0u6AJ5NO3TPH6B-Q

###

GET http://127.0.0.1:8081/api/chats/latestMessages
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODU5Y2Y3OThlNjMzZjUwN2QzZDIyMiIsImlhdCI6MTY4NzE3NDY3Mn0.o0YS2upLJlMwf5IBnbZvJ4eeFVl31ZchKUMB2WDf_aQ

###

GET http://127.0.0.1:8081/api/posts/self
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NzE4OTk4N30.rcOvFrnyHpylJ_yYQ_XJiS_jccYEFFnfacXiQ_89F4M
