# used to test routes
GET http://localhost:8081/api/users

###
GET http://127.0.0.1:8081/api/users/cookie/verify
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODcyMTQ3YmY2ZDk1MzU5OGU4MmRlZSIsImlhdCI6MTY4NjU3ODIxMH0.QW08OASLw_FA4oJs2JDJ0tUxXbk18uqw9qMOwmYA8h4

###
OPTIONS http://localhost:8081/api/users/register

###
POST http://localhost:8081/api/users/register
Content-Type: application/json
credentials: "include"

{
    "emailAddress": "w1111ee@gmail.com",
    "phoneNumber": "111113",
    "password": "123"
}

###

GET http://localhost:3000/api/posts/645f4636e5b42a263b5df79c


###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab",
    "content_links": ["string1", "string2"]
}

###

PATCH http://localhost:3000/api/posts/645f4575e5b42a263b5df79a
Content-Type: application/json

{
    "content_links": "modifiedagain"
}

###

DELETE http://localhost:3000/api/posts/645f4575e5b42a263b5df79a

###

GET http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/comments

###

POST http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab",
    "content": "hello nice post 2"
}

###

DELETE http://localhost:3000/api/posts/645f4636e5b42a263b5df79c/comments/645f8730d46e16b104456e2e

###

POST http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/like
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab"
}

###

DELETE http://localhost:8081/api/posts/645f4636e5b42a263b5df79c/like
Content-Type: application/json

{
    "creator_id": "6021fde84705d830b8f458ab"
}

###

GET http://127.0.0.1:8081/api/posts/comments/647593717e5cbd1fba80f0db
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NTQ1ODk0M30.7QATwzOI8ERXAZPpLgsi0JGfOcMHqnl32IS53hdK9_8

###

DELETE http://127.0.0.1:8081/api/posts/likes/647593717e5cbd1fba80f0db
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NTQ1ODk0M30.7QATwzOI8ERXAZPpLgsi0JGfOcMHqnl32IS53hdK9_8

###

POST http://127.0.0.1:8081/api/posts/comments/647593717e5cbd1fba80f0db
Cookie: authapi=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzU5MjlkZDBiOTdjNWMzNTM2MDJhZiIsImlhdCI6MTY4NTQ1ODk0M30.7QATwzOI8ERXAZPpLgsi0JGfOcMHqnl32IS53hdK9_8
Content-Type: application/json

{
    "content": "new comment",
    "creator_id": "6475929dd0b97c5c353602af"
}